export { default as Background } from './Background/Background';
export { default as DigitalClock } from './clock/DigitalClock';
export { default as Headlines } from './news/Headlines';
export { default as InternationalClock } from './clock/InternationalClock';
export { default as Loader } from './loader/Loader';
export { default as MidnightTrain } from './midnighttrain/MidnightTrain';
export { default as MiniCalendar } from './calendar/MiniCalenar';
export { default as WeatherStrip } from './weather/WeatherStrip';
export { default as Trello } from './todo/Trello';